AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ligify-api
Parameters:
  NcbiApiKey:
    Type: String

Globals:
  Function:
    Timeout: 300
    MemorySize: 1024
    LoggingConfig:
      LogFormat: JSON

Resources:
  LigifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ligify/
      Handler: main.lambda_handler
      Runtime: python3.12
      Environment:
        Variables:
          NcbiApiKey: !Ref NcbiApiKey
      Architectures:
        - arm64
      Events:
        Ligify:
          Type: Api
          Properties:
            Path: /ligify
            Method: ANY  # Change this to ANY
            Cors:
              AllowMethods:  # Use lists instead of strings
                - GET
                - POST
                - OPTIONS
              AllowHeaders:
                - Content-Type
                - Authorization
              AllowOrigin: "http://localhost:3001"
              AllowCredentials: true
