AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ligify-api
Parameters:
  NcbiApiKey:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 1024

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  LigifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ligify/
      Handler: main.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          NcbiApiKey: !Ref NcbiApiKey
      Architectures:
        - arm64
      Events:
        Ligify:
          Type: Api
          Properties:
            Path: /ligify
            Method: post
