AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ligify-api
Parameters:
  NcbiApiKey:
    Type: String

Globals:
  Function:
    # Cloudfront has a hard limit of 178 seconds
    # Trying to return from
    Timeout: 178
    MemorySize: 1024
    LoggingConfig:
      LogFormat: JSON

Resources:
  LigifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: ./ligify/
      ImageConfig:
        Command: ["main.lambda_handler"]
      Environment:
        Variables:
          NcbiApiKey: !Ref NcbiApiKey
      Architectures:
        # x86_64 is required for github actions
        - x86_64
        # Use below for macos local dev
        # - arm64
      FunctionUrlConfig:
        AuthType: NONE
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: LambdaFunctionOrigin
            DomainName: !Select
              - 2
              - !Split
                - '/'
                - !GetAtt LigifyFunctionUrl.FunctionUrl
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultRootObject: ''
        DefaultCacheBehavior:
          TargetOriginId: LambdaFunctionOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # AWS-managed policy: CachingDisabled
          OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac  # AWS-managed policy: AllViewerExceptHostHeader
        CacheBehaviors:
          - PathPattern: /ligify
            TargetOriginId: LambdaFunctionOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # AWS-managed policy: CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac  # AWS-managed policy: AllViewerExceptHostHeader