AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ligify-api
Parameters:
  NcbiApiKey:
    Type: String

Globals:
  Function:
    Timeout: 178
    MemorySize: 1024
    LoggingConfig:
      LogFormat: JSON

Resources:
  LigifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      CodeUri: ./ligify/
      ImageConfig:
        Command: ["main.lambda_handler"]
      Environment:
        Variables:
          NcbiApiKey: !Ref NcbiApiKey
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - GET
            - POST
            - OPTIONS
            - PUT
            - PATCH
            - DELETE
          AllowHeaders:
            - '*'
          AllowCredentials: true
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1

  OriginRequestPolicyAllHeaders:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: 'ForwardAllHeadersPolicy'
        CookiesConfig:
          CookieBehavior: all
        QueryStringsConfig:
          QueryStringBehavior: all
        HeadersConfig:
          HeaderBehavior: allViewer

  ResponseHeadersPolicyCORS:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: 'CORSResponseHeadersPolicy'
        CorsConfig:
          AccessControlAllowOrigins:
            - '*'
          AccessControlAllowHeaders:
            - '*'
          AccessControlAllowMethods:
            - GET
            - POST
            - OPTIONS
            - PUT
            - PATCH
            - DELETE
          OriginOverride: true
          AccessControlAllowCredentials: true

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - Id: LambdaFunctionOrigin
            DomainName: !Select
              - 2
              - !Split
                - '/'
                - !GetAtt LigifyFunctionUrl.FunctionUrl
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultRootObject: ''
        DefaultCacheBehavior:
          TargetOriginId: LambdaFunctionOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: !Ref OriginRequestPolicyAllHeaders
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicyCORS
        CacheBehaviors:
          - PathPattern: /ligify
            TargetOriginId: LambdaFunctionOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: !Ref OriginRequestPolicyAllHeaders
            ResponseHeadersPolicyId: !Ref ResponseHeadersPolicyCORS
