name: Deploy SAM Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Setup SAM
      uses: aws-actions/setup-sam@v2
    
    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

    - name: Deploy SAM application
      run: |
        sam deploy --template-file template.yaml --stack-name ligify --parameter-overrides NcbiApiKey="${{ secrets[format('{0}_NcbiApiKey', env.env)]}}" --no-confirm-changeset --no-fail-on-empty-changeset